version: '3.8'
services:
  app:
    container_name: api-container
    build:
      context: ./webapp
    depends_on:
      - db
    ports:
      - 5001:5000
    tty: true
    environment:
      POSTGRES_URL: postgresql://postgres:postgres@host.docker.internal:5434/dev
      ENV: local

  db:
    container_name: postgres-container
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    ports:
      - 5434:5432
    volumes:
      - ./postgresql/sqls:/docker-entrypoint-initdb.d
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
      TZ: "Asia/Tokyo"
